### ISSUE TITLE
SRS – Sequence Diagram of Basic Use Cases

### ISSUE THREAD

**Issue by defaulterrr** [defaulterrr/hse-skitle#17]

**Comment by Anime-Girl** [comment]
![image](https://user-images.githubusercontent.com/51544746/195585363-c58f5e79-77ed-48d7-9849-668eb6020e59.png)
![image](https://user-images.githubusercontent.com/51544746/195585378-04b55b71-de31-459e-8652-1eb46b38bdd7.png)
