### ISSUE TITLE
Tech Stack – Testing the Product

### ISSUE THREAD

**Issue by defaulterrr** [defaulterrr/hse-skitle#26]

**Comment by kiwikk** [comment]
https://github.com/defaulterrr/hse-skitle/wiki/Testing

**Comment by koalannette** [comment]
Test cases

https://docs.google.com/spreadsheets/d/1qZdclSDuHJm1TBk41TaJ0pP0QbNEF1VTzmTAQJD_b1M/edit#gid=1337405225

**Comment by koalannette** [comment]
Done
