### ISSUE TITLE
HW6 - Domain modeling -2

### ISSUE THREAD

**Issue by koalannette** [defaulterrr/hse-skitle#28]
- [x] Add main and alternative scenarios. Write down textual scenarios in your project repo. 
https://github.com/defaulterrr/hse-skitle/wiki/Use-case-diagram-and-stories
- [x] Prepare CRC cards
- [x] Show a cooperation on a diagram or show as a table
- [x] Update class diagram
Decompose responsibilities from the CRC cards into attributes, associations and operations and add them to the model
- [x] Prepare sequence diagrams according to cooperation diagrams

Report presentation:
https://docs.google.com/presentation/d/1MEOCZj8sqzO_uhOSyfxAsmU9DygUTM3dGGNSY_aILns/edit#slide=id.g164fac20ff7_0_495

**Comment by Anime-Girl** [comment]
Repot uploaded
