### ISSUE TITLE
System reuse - active and passive approach

### ISSUE THREAD

**Issue by koalannette** [defaulterrr/hse-skitle#29]
- [x] Identify and provide the main components and modules of your product 
- [x] For our components, select levels of software reuse (Application System Reuse, Component Reuse, or Function Reuse) 
- [x] For our components, identify which components or modules you have to implement regarding to reuse process models
       −	Software development with reuse (Passive) 
       −	Software development for reuse (Active)

- [ ] Provide requirements and specifications for your new component, then implement it using Active Approach

**Comment by defaulterrr** [comment]
See details in #32
