### ISSUE TITLE
ASD: 1st Module final push

### ISSUE THREAD

**Issue by defaulterrr** [defaulterrr/hse-skitle#33]
## Reports: 
- [x] @defaulterrr T1 – Fix first slides with project description, make the description easier to understand, add features list into the keynote and add github link 
- [x] @syusavelev T2 – Add results into the repository, same goes for T1
- [x] @Anime-Girl  @koalannette T3 – Edit slides 9-10, 12. Add tools into the keynote using the [template] (https://docs.google.com/presentation/d/1ZLAj4YwTQT7AeF0KslYvzDoxudUcs0uRXqDSL7SJ4Sg/edit#slide=id.gebdfeb45a5_0_29) **_(What toots? What presentation?)_**
```
9-10 slides (Functional jobs have valuable attainable results, each on its own.
These are too detailed. 
Its hard ti image a user value of "Wait for the master" job) - поправить Functional jobs @koalannette 
12 slide (Description of services (features) and tasks (jobs) are missing in the repo)
```

- [x] @kiwikk  T4 – Slides without template, usecases, CRUD, fix class diagram

## Github
Wiki in Github should contain following pages:
- [x] @defaulterrr Features 
- [x] @koalannette Personas 
- [x] @Anime-Girl Jobs
- [x] @Anime-Girl  Storymap 
- [x] @kiwikk Use Cases (texts and diagrams) 
- [x] @koalannette Interactions table 
- [x] @koalannette Collaboration diagrams 
- [x] @syusavelev Final Class Diagram with DDD stereotypes
- [x] @defaulterrr Responsibilities table 

## Final Defense
- [x] @defaulterrr @koalannette Plan the keynote (structure, slides) 
- [x] Split the keynote parts between maintainers
- [x] Record the videos
- [x] @defaulterrr Edit the final video

**Comment by koalannette** [comment]
Presentation report:
https://docs.google.com/presentation/d/1o-nEOe8Bx174Yz2YUar4RazR7lJ6bCNlLP2ySgBytLE/edit#slide=id.g1590c0e3bd1_2_105

**Comment by kiwikk** [comment]
Done:

- [X] [Class Diagram](https://github.com/defaulterrr/hse-skitle/wiki/Class-Diagram)
- [X] [Use-Case diagram](https://github.com/defaulterrr/hse-skitle/wiki/Use-case-diagram-and-stories)
- [X] [Task Behavior](https://github.com/defaulterrr/hse-skitle/wiki/Task-Behavior)

To Do:

- [ ] Update Class Diagram description
- [ ] Update Use-Case diagram description
- [ ] Create task behavior description

**Comment by defaulterrr** [comment]
UPD: provided project description in the keynote, added features slide and added those features into the internal wiki

**Comment by kiwikk** [comment]
upd: added (updated) descriptions of diagrams

**Comment by koalannette** [comment]
upd: edited functional jobs, added diagrams to wiki and presentation
